AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 400
WEIGHTS: imagenet
LEARNING_RATE: 0.01
EARLY_STOPPING_PATIENCE : 10
EARLY_STOPPING_MONITOR : val_loss

