artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url : gpiosenka/100-bird-species
  local_data_file: artifacts/data_ingestion/100-bird-species.zip
  unzip_dir: artifacts/data_ingestion
  
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
  
prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  training_data_dir : artifacts/data_ingestion/train
  validation_data_dir : artifacts/data_ingestion/valid

evaluation:
  root_dir:  artifacts/evaluation
  path_of_model: artifacts/training/model.h5
  evaluation_model_dir : artifacts/evaluation/model_dir 
  score_dir : artifacts/evaluation/scores
  test_data: artifacts/data_ingestion/test
  best_model_path : artifacts/evaluation/model_dir/best_model.h5
  mlflow_uri: "https://dagshub.com/princevkurien/Bird_species_classfication.mlflow"

  

