artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url : gpiosenka/100-bird-species
  local_data_file: artifacts/data_ingestion/100-bird-species.zip
  unzip_dir: artifacts/data_ingestion
